services:
  postgres:
    image: postgres:14.5-bullseye
    container_name: database-records
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
